### ISSUE TITLE
investigate loosening the function bounds

### ISSUE THREAD

**Issue by nathan7** [nathan7/libfringe#2]
Currently, `Context::new` takes an `F: FnOnce() + Send + 'static`. This disallows a lot of interesting use-cases. Internally, `Registers::new` only requires `F: FnOnce()`.

It's not clear how `Send` should relate to custom threading runtimes, and this was mostly chosen as a safe bet. We might have to make decisions on how low-level this library should be exactly.

#6 covers the `'static` bound.

**Comment by whitequark** [comment]
Context::new doesn't take these bounds anymore.
