### ISSUE TITLE
swap ... bench: 29 ns/iter (not 6?)

### ISSUE THREAD

**Issue by MarkSwanson** [nathan7/libfringe#58]
$ cargo bench
...
swap ... bench:          29 ns/iter (+/- 0)

I'm curious what CPU was used (and perhaps Rust version?).
I'm using Rust 1.13 nightly
machine: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

Any ideas why I'm 5x slower?

Thanks!

**Comment by Amanieu** [comment]
The benchmark performs 10 context switches in a loop. So it's actually 2.9ns per switch.

**Comment by MarkSwanson** [comment]
Cool.
Ty for responding.

**Comment by Ericson2314** [comment]
Well, we should celebrate that we're now twice as fast as stated :).

**Comment by nathan7** [comment]
@Ericson2314 No, we already state we're at 3ns/switch. The benchmark necessarily measures switches back *and* forth, however.
